include: 
  # pipeline logic
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: v0.11.0

  # build
  - local: "/devops/osdu/compile/seismic-store-sdutil.yml"
  
  # scan
  # scan for secrets
  - local: "/devops/osdu/scanners/scan-for-secrets-python.yml"

  # integration
  - local: "/devops/osdu/integrations/azure.yml"
  
  # fossa
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-python.yml"

  # build
  - local: "devops/osdu/deploy/seismic-store-sdutil.yml"