include: 
  # PIPELINE LOGIC
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  # BUILD
  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/python.yml"

  # overwrite logic
  - local: "/devops/osdu/compile/python.yml"

  # COINTAINERIZE
  - local: "/devops/osdu/containerize/seismic-store-sdutil.yml"

  # SCANNERS
  # ultimate
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  # fossa
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-python.yml"

  # CLOUD PROVIDERS
  # azure
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml" 

  # overwrite logic
  - local: "/devops/osdu/cloud-providers/azure.yml"

  # DEPLOY
  - local: "devops/osdu/deploy/seismic-store-sdutil.yml"
