include: 
  # PIPELINE LOGIC
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  # BUILD
  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/python.yml"
  
  # overwrite logic
  - local: "/devops/osdu/build/python.yml"