include: 
  # PIPELINE LOGIC
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  # BUILD
  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/python.yml"

  # overwrite logic
  - local: "/devops/osdu/compile/python.yml"

  # COINTAINERIZE
  - local: "/devops/osdu/containerize/seismic-store-sdutil.yml"

  # SCANNERS
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  # CLOUD PROVIDERS
  # azure
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml" 