include:
  # pipeline logic
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: v0.26.2

  # build
  - local: "/devops/osdu/compile/seismic-store-sdutil.yml"

  # scan
  # scan for secrets
  - local: "/devops/osdu/scanners/scan-for-secrets-python.yml"

  # vulnerability Scan
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"
    ref: v0.26.2

  # azure-global
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"
    ref: v0.26.2

  # integration
  - local: "/devops/osdu/integrations/azure.yml"

  # fossa
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-python.yml"
    ref: v0.26.2

  # build
  - local: "devops/osdu/deploy/seismic-store-sdutil.yml"
