include: 
  # PIPELINE LOGIC
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  # BUILD
  # build
  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/python.yml"

  # linters
  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/python-linters.yml"

  # overwrite logic
  - local: "/devops/osdu/compile/python.yml"