variables:
  #seismic store service variables\
  E2E_HOSTNAME: ${AZURE_DNS_NAME}
  SDMS_PREFIX: /seistore-svc/api/v3
  E2E_SUBPROJECT: demosandbox08
  E2E_TENANT: $MY_TENANT

sdutil_containerize:
  tags: ["osdu-medium"]
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: containerize
  needs: []
  variables:
    SDUTIL_IMAGE: "seismic-store-sdutil"
    SHA_IMAGE: ${SDUTIL_IMAGE}:${CI_COMMIT_SHA}
    LATEST_IMAGE: ${SDUTIL_IMAGE}:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg python_version="3.10" --build-arg run_tests=true --build-arg E2E_HOSTNAME="${E2E_HOSTNAME}" --build-arg SDMS_PREFIX="${SDMS_PREFIX}" --build-arg E2E_TENANT="${E2E_TENANT}" --build-arg E2E_SUBPROJECT="${E2E_SUBPROJECT}" --build-arg svctoken="${svctoken}" -t ${CI_REGISTRY_IMAGE}/$SHA_IMAGE -f devops/docker/Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}/$SHA_IMAGE
    - |
      if [ "${CI_COMMIT_BRANCH}" == "${CI_DEFAULT_BRANCH}" ]; then
        docker push ${CI_REGISTRY_IMAGE}/$LATEST_IMAGE
      fi
