sdutil_containerize:
  tags: ["osdu-medium"]
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: containerize
  needs: []
  variables:
    SDUTIL_IMAGE: "seismic-store-sdutil"
    SHA_IMAGE: ${SDUTIL_IMAGE}:${CI_COMMIT_SHA}
    LATEST_IMAGE: ${SDUTIL_IMAGE}:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/$SHA_IMAGE -f devops/docker/Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}/$SHA_IMAGE
    - |
      if [ "${CI_COMMIT_BRANCH}" == "${CI_DEFAULT_BRANCH}" ]; then
        docker push ${CI_REGISTRY_IMAGE}/$LATEST_IMAGE
      fi
