compile-and-unit-test:
    stage: build
    image: $CI_REGISTRY_IMAGE/sdutil-osdu-ubuntu
    script:
        - pip3 install -r requirements.txt
        - chmod +x devops/scripts/run_unit_tests.sh
        - ./devops/scripts/run_unit_tests.sh
        - mkdir -p dist
        - rm -rf dist/*
        - cp -r README.md requirements.txt sdlib sdutil sdutil.py dist
    artifacts:
        name: sdutil
        paths:
        - dist/
    
clean-package:
  stage: build
  image: ubuntu
  script:
    - apt-get update
    - apt-get install curl -y
    - apt-get install tar -y
    - apt-get install gzip -y
    - apt-get install git -y
    - apt-get install jq -y
    - version_major=3
    - version_minor=2
    - PACKAGE_VERSION=${version_major}.${version_minor}.$CI_PIPELINE_IID
    - package_id=$(curl --header "JOB-TOKEN:\ $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages" | jq ".[] | select(.version==\"$PACKAGE_VERSION\") | .id")
    - 'curl --request DELETE --header "PRIVATE-TOKEN: $PRIVATE_ACCESS_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/$package_id"'
  only:
    refs:
      - master