# ***************************************************************************
# Copyright 2017-2019, Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ***************************************************************************

oauth2:
  provider: '#{config.oauth2.provider}#'
  authorize_url: '#{config.oauth2.authorize_url}#'
  authorize_params: '#{config.oauth2.authorize_params}#'
  access_token_url: '#{config.oauth2.access_token_url}#'
  access_token_params: '#{config.oauth2.access_token_params}#'
  refresh_token_url: '#{config.oauth2.refresh_token_url}#'
  refresh_token_params: '#{config.oauth2.refresh_token_params}#'
  open_id_url: '#{config.oauth2.open_id_url}#'
  scope: '#{config.oauth2.scope}#'