seistore:
  service: '{"azure": {"azureGlabEnv":{"url": "https://osdu-glab.msft-osdu-test.org/seistore-svc/api/v3", "appkey": ""}}}'
  url: 'https://osdu-glab.msft-osdu-test.org/seistore-svc/api/v3'
  cloud_provider: 'azure'
  env: 'glab'
  auth-mode: 'JWT Token'
  ssl_verify: False
auth_provider:
  azure: '{
         "provider": "azure",
         "authorize_url": "https://login.microsoftonline.com/",
         "oauth_token_host_end": "/oauth2/token",
         "scope_end":"/.default openid profile offline_access",
         "redirect_uri":"http://localhost:8080",
         "login_grant_type": "refresh_token",
         "refresh_token": "<put refresh token here from auth_token.http authorize request>",
         "force_refresh_token": "<true/false, indicates whether sdutil will refresh the token automatically or not>",
         "sdutil_session_timeout": <N hours, after these N hours, token will not be refreshed and you will need to login again once it expires >
         }'
azure:
  empty: 'none'